/**
 * This file is auto-generated by the command "morph build" at 2025-01-22T14:56:10.591Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";
import CrmOpportunityOperationList from "./resources/crmOpportunity/list";
import CrmOpportunityMapper from "./resources/crmOpportunity/mapper";
import CrmOpportunityOperationRetrieve from "./resources/crmOpportunity/retrieve";
import CrmOpportunityOperationUpdate from "./resources/crmOpportunity/update";
import CrmPipelineOperationList from "./resources/crmPipeline/list";
import CrmPipelineMapper from "./resources/crmPipeline/mapper";
import CrmPipelineOperationRetrieve from "./resources/crmPipeline/retrieve";
import CrmStageMapper from "./resources/crmStage/mapper";
import CrmStageOperationRetrieve from "./resources/crmStage/retrieve";
import GenericCompanyMapper from "./resources/genericCompany/mapper";
import GenericCompanyOperationRetrieve from "./resources/genericCompany/retrieve";
import GenericContactOperationCreate from "./resources/genericContact/create";
import GenericContactOperationList from "./resources/genericContact/list";
import GenericContactMapper from "./resources/genericContact/mapper";
import GenericContactOperationRetrieve from "./resources/genericContact/retrieve";
import GenericContactOperationUpdate from "./resources/genericContact/update";
import GenericUserMapper from "./resources/genericUser/mapper";
import GenericUserOperationRetrieve from "./resources/genericUser/retrieve";
import GenericWorkspaceMapper from "./resources/genericWorkspace/mapper";
import GenericWorkspaceOperationRetrieve from "./resources/genericWorkspace/retrieve";
import WidgetCardViewMapper from "./resources/widgetCardView/mapper";
import WebhookGlobalMapper from "./webhooks/global/mapper";
import WebhookGlobalSubscribe from "./webhooks/global/subscribe";
import WebhookGlobalUnsubscribe from "./webhooks/global/unsubscribe";

const resourceModelOperations = {
  crmOpportunity: {
    list: CrmOpportunityOperationList,
    mapper: CrmOpportunityMapper,
    retrieve: CrmOpportunityOperationRetrieve,
    update: CrmOpportunityOperationUpdate,
  },
  crmPipeline: {
    list: CrmPipelineOperationList,
    mapper: CrmPipelineMapper,
    retrieve: CrmPipelineOperationRetrieve,
  },
  crmStage: {
    mapper: CrmStageMapper,
    retrieve: CrmStageOperationRetrieve,
  },
  genericCompany: {
    mapper: GenericCompanyMapper,
    retrieve: GenericCompanyOperationRetrieve,
  },
  genericContact: {
    create: GenericContactOperationCreate,
    list: GenericContactOperationList,
    mapper: GenericContactMapper,
    retrieve: GenericContactOperationRetrieve,
    update: GenericContactOperationUpdate,
  },
  genericUser: {
    mapper: GenericUserMapper,
    retrieve: GenericUserOperationRetrieve,
  },
  genericWorkspace: {
    mapper: GenericWorkspaceMapper,
    retrieve: GenericWorkspaceOperationRetrieve,
  },
  widgetCardView: {
    mapper: WidgetCardViewMapper,
  },
};

const webhookOperations = {
  global: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    mapper: WebhookGlobalMapper as any, // CLI to refactor
    subscribe: WebhookGlobalSubscribe,
    unsubscribe: WebhookGlobalUnsubscribe,
  },
};

const connectorBundle = new ConnectorBundle({
  connector,
  resourceModelOperations,
  webhookOperations,
}).init;

export default connectorBundle;
