/**
 * This file is auto-generated by the command "morph build" at 2025-03-12T17:06:41.528Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";
import GenericContactMapper from "./resources/genericContact/mapper";
import GenericContactOperationList from "./resources/genericContact/list";
import GenericContactOperationRetrieve from "./resources/genericContact/retrieve";
import GenericUserMapper from "./resources/genericUser/mapper";
import GenericUserOperationList from "./resources/genericUser/list";
import GenericUserOperationRetrieve from "./resources/genericUser/retrieve";
import TelephonyCallMapper from "./resources/telephonyCall/mapper";
import TelephonyCallOperationList from "./resources/telephonyCall/list";
import TelephonyCallOperationRetrieve from "./resources/telephonyCall/retrieve";
import WebhookSubscriptionMapper from "./webhooks/subscription/mapper";
import WebhookSubscriptionSubscribe from "./webhooks/subscription/subscribe";
import WebhookSubscriptionUnsubscribe from "./webhooks/subscription/unsubscribe";

const resourceModelOperations = {
  genericContact: {
  list: GenericContactOperationList,
  mapper: GenericContactMapper,
  retrieve: GenericContactOperationRetrieve,
},
  genericUser: {
  list: GenericUserOperationList,
  mapper: GenericUserMapper,
  retrieve: GenericUserOperationRetrieve,
},
  telephonyCall: {
  list: TelephonyCallOperationList,
  mapper: TelephonyCallMapper,
  retrieve: TelephonyCallOperationRetrieve,
},
};


const webhookOperations = {
  subscription: {// eslint-disable-next-line @typescript-eslint/no-explicit-any
  mapper: WebhookSubscriptionMapper as any, // CLI to refactor
  subscribe: WebhookSubscriptionSubscribe,
  unsubscribe: WebhookSubscriptionUnsubscribe,
},
};


const connectorBundle = new ConnectorBundle({
  connector,
  resourceModelOperations,
  webhookOperations,
}).init;

export default connectorBundle;
