import { DefaultFields } from "@runmorph/cdk";

export default new DefaultFields({
  metadataKeys: ["type", "PhoneType"],
  models: {
    genericContact: {
      ContactID: {
        name: "Contact ID",
        description: "Xero identifier (unique within organisations)",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      ContactNumber: {
        name: "Contact Number",
        description:
          "Used to identify contacts in external systems. Displayed as Contact Code in the Contacts UI in Xero.",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      AccountNumber: {
        name: "Account Number",
        description: "A user defined account number",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      ContactStatus: {
        name: "Contact Status",
        description: "Current status of a contact",
        type: "select",
        isRequired: false,
        isValueReadOnly: false,
        optionSource: "static",
        options: [
          {
            name: "Active",
            value: "ACTIVE",
          },
          {
            name: "Archived",
            value: "ARCHIVED",
          },
        ],
        metadata: {},
      },
      Name: {
        name: "Name",
        description: "Full name of contact/organisation",
        type: "text",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      FirstName: {
        name: "First Name",
        description: "First name of contact person",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      LastName: {
        name: "Last Name",
        description: "Last name of contact person",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      EmailAddress: {
        name: "Email Address",
        description: "Email address of contact person",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      BankAccountDetails: {
        name: "Bank Account Details",
        description: "Bank account number of contact",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      CompanyNumber: {
        name: "Company Number",
        description: "Company registration number. Max 50 char.",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      TaxNumber: {
        name: "Tax Number",
        description:
          "Tax number of contact (ABN/GST/VAT/Tax ID depending on region)",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      IsSupplier: {
        name: "Is Supplier",
        description:
          "Boolean that describes if a contact has any AP invoices entered against them",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      IsCustomer: {
        name: "Is Customer",
        description:
          "Boolean that describes if a contact has any AR invoices entered against them",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      DefaultCurrency: {
        name: "Default Currency",
        description: "Default currency for raising invoices against contact",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Website: {
        name: "Website",
        description: "Website address for contact",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      SalesDefaultLineAmountType: {
        name: "Sales Default Line Amount Type",
        description: "The default sales line amount types for contact",
        type: "select",
        isRequired: false,
        isValueReadOnly: false,
        optionSource: "static",
        options: [
          {
            name: "Inclusive",
            value: "INCLUSIVE",
          },
          {
            name: "Exclusive",
            value: "EXCLUSIVE",
          },
          {
            name: "None",
            value: "NONE",
          },
        ],
        metadata: {},
      },
      PurchasesDefaultLineAmountType: {
        name: "Purchases Default Line Amount Type",
        description: "The default purchases line amount types for contact",
        type: "select",
        isRequired: false,
        isValueReadOnly: false,
        optionSource: "static",
        options: [
          {
            name: "Inclusive",
            value: "INCLUSIVE",
          },
          {
            name: "Exclusive",
            value: "EXCLUSIVE",
          },
          {
            name: "None",
            value: "NONE",
          },
        ],
        metadata: {},
      },
      Discount: {
        name: "Discount",
        description: "The default discount rate for the contact",
        type: "number",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Addresses: {
        name: "Addresses",
        description: "List of addresses associated with the contact",
        type: "list.text",
        format: "address",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {
          type: "AddressType",
        },
      },
      Phones: {
        name: "Phones",
        description: "List of phone numbers associated with the contact",
        type: "list.text",
        format: "phone",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {
          type: "PhoneType",
        },
      },
    },
    invoiceItem: {
      ItemID: {
        name: "Item ID",
        description:
          "Xero generated identifier for an item (unique within organisations)",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      Code: {
        name: "Code",
        description: "User defined item code",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Name: {
        name: "Name",
        description: "The name of the item",
        type: "text",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      IsSold: {
        name: "Is Sold",
        description:
          "Boolean value. When IsSold is true the item will be available on sales transactions in the Xero UI",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      IsPurchased: {
        name: "Is Purchased",
        description:
          "Boolean value. When IsPurchased is true the item is available for purchase transactions in the Xero UI",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Description: {
        name: "Description",
        description: "The sales description of the item",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      PurchaseDescription: {
        name: "Purchase Description",
        description: "The purchase description of the item",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      PurchaseDetails: {
        name: "Purchase Details",
        description: "Purchase details for the item",
        type: "object",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      SalesDetails: {
        name: "Sales Details",
        description: "Sales details for the item",
        type: "object",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      IsTrackedAsInventory: {
        name: "Is Tracked As Inventory",
        description:
          "True for items that are tracked as inventory. An item will be tracked as inventory if the InventoryAssetAccountCode and COGSAccountCode are set",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      InventoryAssetAccountCode: {
        name: "Inventory Asset Account Code",
        description:
          "The inventory asset account for the item. The account must be of type INVENTORY. The COGSAccountCode in PurchaseDetails is also required to create a tracked item",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      TotalCostPool: {
        name: "Total Cost Pool",
        description:
          "The value of the item on hand. Calculated using average cost accounting",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      QuantityOnHand: {
        name: "Quantity On Hand",
        description: "The quantity of the item on hand",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      UpdatedDateUTC: {
        name: "Updated Date UTC",
        description: "Last modified date in UTC format",
        type: "datetime",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
    },
    invoice: {
      InvoiceID: {
        name: "Invoice ID",
        description:
          "Xero generated identifier for invoice (unique within organisations)",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      Type: {
        name: "Type",
        description: "Invoice type (ACCREC or ACCPAY)",
        type: "select",
        isRequired: true,
        isValueReadOnly: false,
        optionSource: "static",
        options: [
          {
            name: "Accounts Receivable",
            value: "ACCREC",
            description:
              "A sales invoice – commonly known as an Accounts Receivable or customer invoice",
          },
          {
            name: "Accounts Payable",
            value: "ACCPAY",
            description:
              "A bill – commonly known as an Accounts Payable or supplier invoice",
          },
        ],
        metadata: {},
      },

      Date: {
        name: "Date",
        description: "Date invoice was issued – YYYY-MM-DD",
        type: "date",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      DueDate: {
        name: "Due Date",
        description: "Date invoice is due – YYYY-MM-DD",
        type: "date",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      Status: {
        name: "Status",
        description: "Current status of the invoice",
        type: "select",
        isRequired: true,
        isValueReadOnly: false,
        optionSource: "static",
        options: [
          {
            name: "Draft",
            value: "DRAFT",
            description: "A Draft Invoice (default)",
          },
          {
            name: "Submitted",
            value: "SUBMITTED",
            description: "An Awaiting Approval Invoice",
          },
          {
            name: "Authorised",
            value: "AUTHORISED",
            description:
              "An Invoice that is Approved and Awaiting Payment OR partially paid",
          },
          {
            name: "Paid",
            value: "PAID",
            description: "An Invoice that is completely Paid",
          },
          { name: "Voided", value: "VOIDED", description: "A Voided Invoice" },
          {
            name: "Deleted",
            value: "DELETED",
            description: "A Deleted Invoice",
          },
        ],
        metadata: {},
      },
      LineAmountTypes: {
        name: "Line Amount Types",
        description: "Type of line amounts in the invoice",
        type: "select",
        isRequired: true,
        isValueReadOnly: false,
        optionSource: "static",
        options: [
          {
            name: "Exclusive",
            value: "Exclusive",
            description: "Line items are exclusive of tax",
          },
          {
            name: "Inclusive",
            value: "Inclusive",
            description: "Line items are inclusive tax",
          },
          { name: "NoTax", value: "NoTax", description: "Line have no tax" },
        ],
        metadata: {},
      },

      SubTotal: {
        name: "Sub Total",
        description: "Total of invoice excluding taxes",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      TotalTax: {
        name: "Total Tax",
        description: "Total tax on invoice",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      Total: {
        name: "Total",
        description:
          "Total of Invoice tax inclusive (i.e. SubTotal + TotalTax)",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      TotalDiscount: {
        name: "Total Discount",
        description: "Total of discounts applied on the invoice line items",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      UpdatedDateUTC: {
        name: "Updated Date UTC",
        description: "Last modified date UTC format",
        type: "datetime",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      CurrencyCode: {
        name: "Currency Code",
        description: "The currency that invoice has been raised in",
        type: "text",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      CurrencyRate: {
        name: "Currency Rate",
        description: "The currency rate for a multicurrency invoice",
        type: "number",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      InvoiceNumber: {
        name: "Invoice Number",
        description:
          "Unique alpha numeric code identifying invoice (printable ASCII characters only)",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Reference: {
        name: "Reference",
        description: "Additional reference number (ACCREC only)",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      BrandingThemeID: {
        name: "Branding Theme ID",
        description: "ID of the branding theme applied to the invoice",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Url: {
        name: "URL",
        description:
          "URL link to a source document – shown as 'Go to [appName]' in the Xero app",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      SentToContact: {
        name: "Sent To Contact",
        description:
          "Boolean to indicate whether the invoice in the Xero app displays as 'sent'",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      ExpectedPaymentDate: {
        name: "Expected Payment Date",
        description:
          "Shown on sales invoices (Accounts Receivable) when this has been set",
        type: "date",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      PlannedPaymentDate: {
        name: "Planned Payment Date",
        description: "Shown on bills (Accounts Payable) when this has been set",
        type: "date",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      HasAttachments: {
        name: "Has Attachments",
        description: "Boolean to indicate if an invoice has an attachment",
        type: "boolean",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      RepeatingInvoiceID: {
        name: "Repeating Invoice ID",
        description:
          "Xero generated identifier for repeating invoice template (unique within organisations)",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },

      AmountDue: {
        name: "Amount Due",
        description: "Amount remaining to be paid on invoice",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      AmountPaid: {
        name: "Amount Paid",
        description: "Sum of payments received for invoice",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      CISDeduction: {
        name: "CIS Deduction",
        description:
          "CISDeduction withheld by the contractor to be paid to HMRC on behalf of subcontractor (Available for organisations under UK Construction Industry Scheme)",
        type: "number",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      FullyPaidOnDate: {
        name: "Fully Paid On Date",
        description:
          "The date the invoice was fully paid. Only returned on fully paid invoices",
        type: "date",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      AmountCredited: {
        name: "Amount Credited",
        description:
          "Sum of all credit notes, over-payments and pre-payments applied to invoice",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      SalesTaxCalculationTypeCode: {
        name: "Sales Tax Calculation Type Code",
        description:
          "Tax calculation type. Only applicable for organisations in the US",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      InvoiceAddresses: {
        name: "Invoice Addresses",
        description:
          "Addresses associated with the invoice. Only applicable for organisations in the US",
        type: "list.text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {
          type: "AddressType",
        },
      },
    },
    invoiceLineItem: {
      Description: {
        name: "Description",
        description: "The description of the line item",
        type: "text",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      Quantity: {
        name: "Quantity",
        description: "LineItem Quantity",
        type: "number",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      UnitAmount: {
        name: "Unit Amount",
        description:
          "Lineitem unit amount. By default, unit amount will be rounded to two decimal places. You can opt in to use four decimal places by adding the querystring parameter unitdp=4 to your query.",
        type: "number",
        isRequired: true,
        isValueReadOnly: false,
        metadata: {},
      },
      ItemCode: {
        name: "Item Code",
        description: "Code of the item",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      AccountCode: {
        name: "Account Code",
        description: "Code of the account",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      AccountId: {
        name: "Account ID",
        description: "ID of the account",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      Item: {
        name: "Item",
        description: "Details of the item",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      LineItemID: {
        name: "Line Item ID",
        description: "The Xero generated identifier for a LineItem",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      TaxType: {
        name: "Tax Type",
        description:
          "Used as an override if the default Tax Code for the selected AccountCode is not correct",
        type: "text",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      TaxAmount: {
        name: "Tax Amount",
        description:
          "The tax amount is auto calculated as a percentage of the line amount based on the tax rate",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      LineAmount: {
        name: "Line Amount",
        description:
          "The line amount reflects the discounted price if a DiscountRate has been used i.e LineAmount = Quantity * Unit Amount * ((100 – DiscountRate)/100)",
        type: "number",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      DiscountRate: {
        name: "Discount Rate",
        description:
          "Percentage discount being applied to a line item. Only supported on ACCREC invoices and quotes. ACCPAY invoices and credit notes in Xero do not support discounts",
        type: "number",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },
      DiscountAmount: {
        name: "Discount Amount",
        description:
          "Discount amount being applied to a line item. Only supported on ACCREC invoices and quotes. ACCPAY invoices and credit notes in Xero do not support discounts",
        type: "number",
        isRequired: false,
        isValueReadOnly: false,
        metadata: {},
      },

      SalesTaxCodeID: {
        name: "Sales Tax Code ID",
        description:
          "Only applicable for organisations in the US - Invoices with an auto sales tax calculation type are read only",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      Taxability: {
        name: "Taxability",
        description:
          "Only applicable for organisations in the US - Invoices with an auto sales tax calculation type are read only",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
      TaxBreakdown: {
        name: "Tax Breakdown",
        description:
          "Only applicable for organisations in the US - Invoices with an auto sales tax calculation type are read only",
        type: "text",
        isRequired: false,
        isValueReadOnly: true,
        metadata: {},
      },
    },
  },
});
