/**
 * This file is auto-generated by the command "morph build" at 2025-01-06T14:33:47.090Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";
import CrmOpportunityOperationList from "./resources/crmOpportunity/list";
import CrmOpportunityMapper from "./resources/crmOpportunity/mapper";
import CrmOpportunityOperationRetrieve from "./resources/crmOpportunity/retrieve";
import CrmOpportunityOperationUpdate from "./resources/crmOpportunity/update";
import CrmPipelineOperationList from "./resources/crmPipeline/list";
import CrmPipelineMapper from "./resources/crmPipeline/mapper";
import CrmPipelineOperationRetrieve from "./resources/crmPipeline/retrieve";
import CrmStageMapper from "./resources/crmStage/mapper";
import CrmStageOperationRetrieve from "./resources/crmStage/retrieve";
import GenericContactMapper from "./resources/genericContact/mapper";
import GenericContactOperationRetrieve from "./resources/genericContact/retrieve";
import GenericUserMapper from "./resources/genericUser/mapper";
import GenericUserOperationRetrieve from "./resources/genericUser/retrieve";
import GenericWorkspaceMapper from "./resources/genericWorkspace/mapper";
import GenericWorkspaceOperationRetrieve from "./resources/genericWorkspace/retrieve";

const resourceModelOperations = {
  crmOpportunity: {
    list: CrmOpportunityOperationList,
    mapper: CrmOpportunityMapper,
    retrieve: CrmOpportunityOperationRetrieve,
    update: CrmOpportunityOperationUpdate,
  },
  crmPipeline: {
    list: CrmPipelineOperationList,
    mapper: CrmPipelineMapper,
    retrieve: CrmPipelineOperationRetrieve,
  },
  crmStage: {
    mapper: CrmStageMapper,
    retrieve: CrmStageOperationRetrieve,
  },
  genericContact: {
    mapper: GenericContactMapper,
    retrieve: GenericContactOperationRetrieve,
  },
  genericUser: {
    mapper: GenericUserMapper,
    retrieve: GenericUserOperationRetrieve,
  },
  genericWorkspace: {
    mapper: GenericWorkspaceMapper,
    retrieve: GenericWorkspaceOperationRetrieve,
  },
};

const connectorBundle = new ConnectorBundle({
  connector,
  resourceModelOperations,
}).init;

export default connectorBundle;
