/**
 * This file is auto-generated by the command "morph build" at 2025-06-04T12:37:35.691Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";
import AccountingInvoiceItemMapper from "./resources/accountingInvoiceItem/mapper";
import AccountingInvoiceItemOperationList from "./resources/accountingInvoiceItem/list";
import AccountingInvoiceItemOperationRetrieve from "./resources/accountingInvoiceItem/retrieve";
import AccountingInvoiceLineItemMapper from "./resources/accountingInvoiceLineItem/mapper";
import AccountingInvoiceLineItemOperationRetrieve from "./resources/accountingInvoiceLineItem/retrieve";
import AccountingInvoiceMapper from "./resources/accountingInvoice/mapper";
import AccountingInvoiceOperationList from "./resources/accountingInvoice/list";
import AccountingInvoiceOperationRetrieve from "./resources/accountingInvoice/retrieve";
import GenericContactMapper from "./resources/genericContact/mapper";
import GenericContactOperationList from "./resources/genericContact/list";
import GenericContactOperationRetrieve from "./resources/genericContact/retrieve";
import fieldMapper from "./fields/mapper";

const resourceModelOperations = {
  accountingInvoice: {
  list: AccountingInvoiceOperationList,
  mapper: AccountingInvoiceMapper,
  retrieve: AccountingInvoiceOperationRetrieve,
},
  accountingInvoiceItem: {
  list: AccountingInvoiceItemOperationList,
  mapper: AccountingInvoiceItemMapper,
  retrieve: AccountingInvoiceItemOperationRetrieve,
},
  accountingInvoiceLineItem: {
  mapper: AccountingInvoiceLineItemMapper,
  retrieve: AccountingInvoiceLineItemOperationRetrieve,
},
  genericContact: {
  list: GenericContactOperationList,
  mapper: GenericContactMapper,
  retrieve: GenericContactOperationRetrieve,
},
};



const fieldOperations = {
  mapper: fieldMapper,
};

const connectorBundle = new ConnectorBundle({
  connector,
  resourceModelOperations,
  fieldOperations,
}).init;

export default connectorBundle;
