/**
 * This file is auto-generated by the command "morph build" at 2025-01-03T20:20:10.199Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";

const resourceModelOperations = {};

const connectorBundle = new ConnectorBundle({
  connector,
  resourceModelOperations,
}).init;

export default connectorBundle;
