/**
 * This file is auto-generated by the command "morph build" at 2024-11-29T09:22:13.025Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";


const resourceModelOperations = {
  
};



export default new ConnectorBundle({
  connector,
  resourceModelOperations,
}).init;
