/**
 * This file is auto-generated by the command "morph build" at 2025-03-15T08:43:57.770Z
 * Please do not modify it manually.
 */
import { ConnectorBundle } from "@runmorph/cdk";

import connector from "./connector";
import SchedulingEventMapper from "./resources/schedulingEvent/mapper";
import SchedulingEventTypeMapper from "./resources/schedulingEventType/mapper";
import SchedulingEventTypeOperationList from "./resources/schedulingEventType/list";
import SchedulingEventTypeOperationRetrieve from "./resources/schedulingEventType/retrieve";
import SchedulingSlotMapper from "./resources/schedulingSlot/mapper";
import SchedulingSlotOperationList from "./resources/schedulingSlot/list";

const resourceModelOperations = {
  schedulingEvent: {
  mapper: SchedulingEventMapper,
},
  schedulingEventType: {
  list: SchedulingEventTypeOperationList,
  mapper: SchedulingEventTypeMapper,
  retrieve: SchedulingEventTypeOperationRetrieve,
},
  schedulingSlot: {
  list: SchedulingSlotOperationList,
  mapper: SchedulingSlotMapper,
},
};



const connectorBundle = new ConnectorBundle({
  connector,
  resourceModelOperations,
}).init;

export default connectorBundle;
